GET http://localhost:8001/users/ax@gmail.com  HTTP/1.1

###
GET http://localhost:8080/ HTTP/1.1

###
GET http://localhost:8080/err

###
GET http://localhost:8080/users/ax@gmail.com

### 
GET http://localhost:8080/posts/ax@gmail.com

###
GET http://localhost:8080/users/weak@ex.com


###
DELETE http://localhost:8080/users/t@ex.com

###
POST  http://localhost:8080/users 
Content-Type: application/json

{
    "email":"weak@ex.com",
    "name":"weak",
    "password":"pww12&_Tr99!",
    "age":"19"
}

### 
POST http://localhost:8080/login
Content-Type: application/json

{
    "email":"ax@gmail.com",
    "password":"pd"
}